[env:esp32-c6-devkitc-1]
platform = https://github.com/Jason2866/platform-espressif32.git
board = esp32-c6-devkitc-1
framework = espidf
monitor_speed = 115200

board_build.flash_size = 8MB
board_build.partitions = partitions.csv
board_upload.flash_size = 8MB

board_upload.offset = 0x20000
