listener 8883
protocol mqtt

cafile /home/daniela101/ws/man-down/fog_node/certs/ca.crt
certfile /home/daniela101/ws/man-down/fog_node/certs/server.crt
keyfile /home/daniela101/ws/man-down/fog_node/certs/server.key

require_certificate false
allow_anonymous true