#pragma once

// ===== WiFi =====
#define WIFI_SSID "Tele2_333f71_2.4Ghz"
#define WIFI_PASS "qdzjtnwi"
#define DEVICE_ID 2

// ===== MQTT =====
#define BROKER_IP "mqtts://192.168.0.29:8883"
#define MQTT_BROKER "192.168.0.29"
#define MQTT_PORT "8883"
#define MQTT_USERNAME "mesh_node_2"
#define MQTT_PASSWORD "dev"
#define PUB_TOPIC "mesh/node/2/edge"

// ===== TLS =====
static const char ca_cert[] = R"EOF(
-----BEGIN CERTIFICATE-----
MIIDCTCCAfGgAwIBAgIUdlZ2EXdWd7Dsqapvvyr4G032dicwDQYJKoZIhvcNAQEL
BQAwFDESMBAGA1UEAwwJTGVnYWN5LUNBMB4XDTI2MDQyMDExNDQ0OFoXDTI3MDQy
MDExNDQ0OFowFDESMBAGA1UEAwwJTGVnYWN5LUNBMIIBIjANBgkqhkiG9w0BAQEF
AAOCAQ8AMIIBCgKCAQEAymPpt0O9KlAJhot22bOwmZ/bDaWZr+xyDjcqzM/LUuqg
uDnWxSKlsgiZrU8+D2JALEDnoXZ63vrr6oNF6B2R/6oyTGMwaPU3OqdM+mKBncCd
TmNcqo+pDGgtwgiqYQsiGyWBSmfApsRJj4RL1HQHIeMo6ZPjdKMiqzO3P6A2Izn0
a38FpirE6nPN/zBZnTkN4lEoHoFcxF2TVsJtuZsM/Q7cbQbeW8XK45YGpjSwujhD
FSTMvgKpTX+8sXg5QxfpleKoBblF8XeV4x8eHrxiuIK2/clU3PGsEeAK81W0qDCH
hefmAgaNQEjU3KaPfK7NaS5Fl5CQlKejDASZbaPlqQIDAQABo1MwUTAdBgNVHQ4E
FgQUlDYW0z72cv0gVAPcOzatvgg9PygwHwYDVR0jBBgwFoAUlDYW0z72cv0gVAPc
Ozatvgg9PygwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEANMP8
JNvaZdpGb0mT/FLQjqyHoXxuUzUEcwJE7rOZWpvYxA885wKaDtIEGq5vUZXW7iVP
gRNnVQe85c2FDmNyAUnCVf6OKm3VhODsnJPuU/G8ThH+MlcnG7JTqhJ80WGss1X6
wzntuwCwu8keFf+PdWlSOAIuAODueZX8k5guifRHCENjdvkWzNhIIZLLg5KGKUmG
u1pzOVZq/j5jy1TrAlGCTykt4mpEWz4duKBo9ULMIUBqOfD6GEHTJPZUFWLvXcca
mkFvFgytILS0d8ecESepRUafIDZHSl1/FmXbZy9DPeojjuQWDdfYDgCSU6NpbWiP
HmhSpPJIYv71EoIevQ==
-----END CERTIFICATE-----
)EOF";
